export const nftPoolAbi = [
  'function SMART_CHEF_FACTORY() view returns (address)',
  'function owner() view returns (address)',
  'function stakedToken() view returns (address)',
  'function rewardToken() view returns (address)',
  'function sideRewardTokens(uint256) view returns (address)',
  'function sideRewardPercentage(address) view returns (uint256)',
  'function isSideRewardActive() view returns (bool)',
  'function rewardPerBlock() view returns (uint256)',
  'function startBlock() view returns (uint256)',
  'function bonusEndBlock() view returns (uint256)',
  'function poolLimitPerUser() view returns (uint256)',
  'function numberBlocksForUserLimit() view returns (uint256)',
  'function poolCapacity() view returns (uint256)',
  'function participantThreshold() view returns (uint256)',
  'function collectionWeights(address) view returns (uint256)',
  'function communityCollections(uint256) view returns (address)',
  'function performanceFee() view returns (uint256)',
  'function feeTo() view returns (address)',
  'function setCollectionWeights(address[],uint256[],uint256)',
  'function setPerformanceFee(address,uint256)',
  'function updateStartAndEndBlocks(uint256,uint256)',
]
